name: Prowler Security Scan

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Prowler
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler
          # Optionally, install dependencies if needed

      - name: Run Prowler Scan
        id: prowler
        run: |
          cd prowler
          ./prowler -c check135 > report.txt  # Adjust checks as needed
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
