name: Prowler Scan and Notifications

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prowler-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}  # Optional

      - name: Test AWS CLI Configuration
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS Account ID: $ACCOUNT_ID"

      - name: Run Prowler
        run: |
          mkdir -p ./prowler-reports
          ./prowler -M json -o ./prowler-reports/report.json

      - name: Check for Vulnerabilities and Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          if [ -f "./prowler-reports/report.json" ]; then
              VULNERABILITIES=$(jq '.[] | select(.result == "FAIL")' ./prowler-reports/report.json)

              if [ -n "$VULNERABILITIES" ]; then
                  curl -X POST -H 'Content-type: application/json' --data '{
                      "text": "🚨 Prowler Scan Alert! Vulnerabilities Detected:\n'"$VULNERABILITIES"'"
                  }' $SLACK_WEBHOOK_URL
                  echo "Alert sent to Slack!"
              else
                  echo "No vulnerabilities detected."
              fi
          else
              echo "Report generation failed!"
              exit 1
          fi
