name: Prowler Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prowler-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}  # Optional

      - name: Test AWS CLI Configuration
        run: aws sts get-caller-identity

      - name: Run Prowler
        run: |
          # Create output directory for reports
          mkdir -p ./prowler-reports
          # Run Prowler
          ./prowler -M csv -o ./prowler-reports/report.csv

      - name: Send Report to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BEARER_TOKEN: ${{ secrets.SLACK_BEARER_TOKEN }}
        run: |
          REPORT_FILE="./prowler-reports/report.csv"
          if [ -f "$REPORT_FILE" ]; then
              curl -F file=@"$REPORT_FILE" \
                   -F "initial_comment=AWS Security Report" \
                   -F channels=#your-channel \
                   -H "Authorization: Bearer $SLACK_BEARER_TOKEN" \
                   https://slack.com/api/files.upload
              echo "Report sent to Slack!"
          else
              echo "Report generation failed!"
              exit 1
          fi
