name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Prowler
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler

      - name: List Prowler Directory
        run: |
          cd prowler
          ls -lR  # List all files recursively to see the structure

      - name: Identify Executable
        run: |
          cd prowler
          # Find the correct executable file by listing files again
          find . -type f -exec ls -l {} \;  # List all files with details

      - name: Run Prowler Scan
        id: prowler
        run: |
          cd prowler
          # Replace 'check_prowler.sh' with the actual name found in the previous step
          chmod +x ./check_prowler.sh  # Make sure this matches the actual script name
          ./check_prowler.sh -c check135 > report.txt  # Adjust if necessary
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
