name: Terraform and Prowler CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  # Optional, for temporary credentials
        run: echo "AWS credentials are set."

      - name: Terraform Init
        run: |
          cd terraform  # Change to your Terraform directory if needed
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform  # Change to your Terraform directory if needed
          terraform plan

      - name: Terraform Apply
        run: |
          cd terraform  # Change to your Terraform directory if needed
          terraform apply -auto-approve

      - name: Checkout Prowler
        run: git clone https://github.com/salesforce/prowler.git

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq

      - name: Run Prowler
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}  
        run: |
          cd prowler
          ./prowler -q
