name: Prowler Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Install Prowler and Dependencies
        run: |
          pip install --upgrade pip
          pip install prowler
          pip install "pyOpenSSL>=22.0.0" "urllib3>=1.26.0"

      - name: Run Prowler Security Audit
        env:
          ACCOUNT_ID: ${{ secrets.TARGET_ACCOUNT_ID }}
        run: |
          ulimit -n 4096
          mkdir -p output
          for ACCOUNTID in $ACCOUNT_ID; do
          {
            echo "Scanning account: $ACCOUNTID"
            prowler aws \
              --role arn:aws:iam::$ACCOUNTID:role/ProwlerExecRole \
              --output-directory ./output \
              --output-modes html csv json-asff \
              --ignore-exit-code-3
          }
          done

      - name: List Prowler Output
        run: |
          ls -l ./output

      - name: Upload Prowler Results to S3
        run: |
          aws s3 cp ./output/ "s3://${{ secrets.S3_BUCKET_NAME }}/" --recursive

      - name: Debugging Outputs
        run: |
          echo "Verifying S3 bucket contents:"
          aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}/
