name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Prowler
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler

      - name: List Prowler Directory
        run: |
          cd prowler
          ls -lR  # List all files recursively to see the structure

      - name: Identify Prowler Executable
        id: identify
        run: |
          cd prowler
          # Assuming 'prowler' is a directory, look for executable scripts within it
          ls -lR prowler

      - name: Run Prowler Scan
        id: prowler
        run: |
          cd prowler
          # Use the correct script based on the output from the previous step
          chmod +x ./prowler/check_prowler.sh  # Update this based on actual structure
          ./prowler/check_prowler.sh -c check135 > report.txt  # Update based on actual structure
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
