name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Prowler
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler

      - name: List All Files
        run: |
          cd prowler
          find . -print  # This will print all files and directories in the prowler folder

      - name: List Detailed Structure
        run: |
          cd prowler
          ls -lR  # List all files and directories recursively with details

      - name: Run Prowler Scan
        id: prowler
        run: |
          cd prowler
          # Make sure to replace 'check_prowler.sh' with the actual script found in previous steps
          chmod +x ./check_prowler.sh  # Adjust this line based on the actual executable name
          ./check_prowler.sh -c check135 > report.txt  # Adjust if necessary
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
