      - name: Send Reports to Slack
        if: env.scan_status == 'success'
        run: |
          # List current directory contents for debugging
          echo "Current directory contents:"
          ls -l

          # Ensure files exist before reading
          report_file_json="report_all_checks.json"
          report_file_csv="report_all_checks.csv"

          if [[ ! -f "$report_file_json" || ! -f "$report_file_csv" ]]; then
            echo "One or both report files do not exist."
            exit 1
          fi
          
          echo "Sending reports to Slack..."

          # Send JSON report as a text message
          content_json=$(<"$report_file_json")
          payload_json=$(jq -n --arg text "*Prowler Scan Report for All Checks*\n\n*JSON Report:*\n\`\`\`$content_json\`\`\`" '{text: $text}')

          response_json=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H 'Content-type: application/json' --data "$payload_json" "${{ secrets.SLACK_WEBHOOK_URL }}")

          if [ "$response_json" -ne 200 ]; then
            echo "Failed to send JSON report to Slack. HTTP status code: $response_json"
            exit 1
          else
            echo "JSON report sent to Slack successfully."
          fi

          # Upload CSV report as a file
          curl -F file=@"$report_file_csv" \
               -F "initial_comment=Here is the Prowler scan CSV report." \
               -F channels="${{ secrets.SLACK_CHANNEL_ID }}" \
               -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
               https://slack.com/api/files.upload

