name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Prowler
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler

      - name: List Prowler Directory
        run: |
          cd prowler
          ls -lR  # List all files and directories recursively

      - name: Identify Executable Files
        run: |
          cd prowler
          find . -type f -executable  # Find all executable files

      - name: Run Prowler Scan
        run: |
          cd prowler
          # Replace with the correct script name you find in the previous step
          chmod +x ./check_prowler.sh  # Adjust this line based on the actual script name
          ./check_prowler.sh -c check135 > report.txt  # Adjust if necessary
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
