name: Prowler Scan

on:
  push:
    branches:
      - main
      
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions
          aws-region: us-east-1
         
      - name: Installing Prowler Dependencies
        run: |
          sudo apt-get update
          sudo apt install zip unzip python3-pip -y
          sudo apt remove python3-urllib3 -y
          python3 -m pip install --upgrade pip
          python3 -m pip install prowler matplotlib pandas numpy requests slack-sdk plotly
          ulimit -n 4096
          prowler --version
        
      - name: Running Security Audit on AWS
        env:
          ACCOUNT_ID: ${{ secrets.TARGET_ACCOUNT_ID }}
        run: |
          for ACCOUNTID in $ACCOUNT_ID; do
          {
            echo $ACCOUNTID
            prowler aws \
              --role arn:aws:iam::$ACCOUNTID:role/ProwlerExecRole \
              --output-directory /home/runner/work/prowler/prowler/output \
              --output-modes html csv json-asff \
              --ignore-exit-code-3
          }
          done
          aws s3 cp /home/runner/work/prowler/prowler/output/ "s3://${{ secrets.S3_BUCKET_NAME }}/" --recursive
           
      - name: List Prowler Output
        run: ls -l /home/runner/work/prowler/prowler/output

      - name: Upload Prowler Results to S3
        run: |
          aws s3 cp /home/runner/work/prowler/prowler/output/ s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive

      - name: Debugging Outputs
        run: |
          echo "Verifying S3 bucket contents:"
          aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}/
