name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-22.04  # Use a specific version for better compatibility

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clean Environment
        run: |
          pip uninstall -y prowler boto3 botocore cryptography pyOpenSSL

      - name: Install Prowler with Compatible Versions
        run: |
          pip install --upgrade pip  # Upgrade pip to the latest version
          pip install "boto3>=1.26.17,<1.27.0" "botocore>=1.29.0,<1.30.0" prowler 

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
          aws configure set region us-east-1  # Change this to your desired region

      - name: Run Prowler Scan
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          for check in check135; do  # You can add more checks if needed
            echo "Running check: $check"
            if timeout 300 prowler aws -c "$check" --output-formats json-asff,csv --verbose > "report_$check.txt" 2> "error_$check.log"; then
              echo "Check $check completed successfully."
            else
              echo "Check $check failed. See error log for details:"
              cat "error_$check.log"  # Output the error log for troubleshooting
              exit 1
            fi
          done
          echo "All scans complete, generated reports:"
          ls -l report_*.txt prowler-output-*.json prowler-output-*.csv  # List generated report files

      - name: Send Reports to Slack
        run: |
          if ls report_*.txt 1> /dev/null 2>&1; then
            for report in report_*.txt; do
              content=$(<"$report")  # Read file content
              curl -X POST -H 'Content-type: application/json' --data "{
                \"text\": \"*Prowler Alert: Vulnerabilities Detected for ${report}*\\n\`\`\`${content}\`\`\`\"
              }" "${{ secrets.SLACK_WEBHOOK_URL }}"
            done
          else
            echo "No report files found to send to Slack."
          fi
