name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH

      - name: Install Prowler and Dependencies
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler
          poetry install  # Install all dependencies listed in pyproject.toml

      - name: Run Prowler Scan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          cd prowler
          for check in check135; do  # You can add more checks if needed
            echo "Running check: $check"
            poetry run python ./prowler.py -c "$check" > "report_$check.txt"
          done
          echo "All scans complete, generated reports:"
          ls -l report_*.txt  # List generated report files

      - name: Send Reports to Slack
        run: |
          if ls report_*.txt 1> /dev/null 2>&1; then
            for report in report_*.txt; do
              content=$(cat "$report")
              curl -X POST -H 'Content-type: application/json' --data "{
                \"text\": \"*Prowler Alert: Vulnerabilities Detected for ${report}*\\n\`\`\`${content}\`\`\`\"
              }" "${{ secrets.SLACK_WEBHOOK_URL }}"
            done
          else
            echo "No report files found to send to Slack."
          fi
