name: Prowler Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clean Environment
        run: |
          pip uninstall -y prowler boto3 botocore cryptography pyOpenSSL urllib3 || true

      - name: Install Prowler and Dependencies
        run: |
          pip install --upgrade pip
          pip install prowler
          pip install "pyOpenSSL>=22.0.0" "urllib3>=1.26.0"

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"

      - name: Run Prowler JSON Scan
        id: prowler_json_scan
        run: |
          set -e
          report_prefix="prowler-output-$(date +%Y%m%d%H%M%S)"
          report_file_json="${report_prefix}.ocsf.json"
          report_file_csv="${report_prefix}.csv"
          error_file="error_json.log"

          echo "Running Prowler JSON checks..."

          if timeout 1200 prowler aws -c all --output-formats json-ocsf --output-filename "$report_prefix" --verbose > "$error_file" 2>&1; then
            echo "JSON report created successfully."
          else
            echo "JSON checks failed. See error log for details:" | tee -a "$error_file"
            cat "$error_file"
            exit 1
          fi

      - name: Run Prowler CSV Scan
        id: prowler_csv_scan
        run: |
          set -e
          report_prefix="prowler-output-$(date +%Y%m%d%H%M%S)"
          report_file_csv="${report_prefix}.csv"
          error_file="error_csv.log"

          echo "Running Prowler CSV checks..."

          if timeout 2400 prowler aws -c all --output-formats csv --output-filename "$report_prefix" --verbose > "$error_file" 2>&1; then
            echo "CSV report created successfully."
          else
            echo "CSV checks failed. See error log for details:" | tee -a "$error_file"
            cat "$error_file"
            exit 1
          fi

      - name: Show Error Log
        if: failure()
        run: |
          echo "Error Log Contents:"
          if [[ -f error_json.log ]]; then
            cat error_json.log
          fi
          if [[ -f error_csv.log ]]; then
            cat error_csv.log
          fi

      - name: Send Reports to Slack
        run: |
          echo "Sending reports to Slack..."

          report_summary=$(cat error_json.log || echo "No errors in JSON scan.")
          report_summary+=$'\n\n'
          report_summary+=$(cat error_csv.log || echo "No errors in CSV scan.")

          payload=$(jq -n --arg text "$report_summary" '{text: $text}')
          webhook_url="${{ secrets.SLACK_WEBHOOK_URL }}"

          # Send the report summary to Slack
          curl -s -X POST -H 'Content-type: application/json' --data "$payload" "$webhook_url"

          # Attach report files if they exist
          for file in prowler-output-*.ocsf.json prowler-output-*.csv; do
            if [[ -f "$file" ]]; then
              curl -F file=@${file} -F "initial_comment=Here is the Prowler report: $file" -F channels=${{ secrets.SLACK_CHANNEL_ID }} "$webhook_url"
            fi
          done
