name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add Poetry to PATH

      - name: Install Prowler and Dependencies
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler
          poetry install --no-root  # Install dependencies without installing the project itself

      - name: List Prowler Directory
        run: |
          cd prowler
          ls -lR  # List all files and directories recursively

      - name: Identify Executable Files
        run: |
          cd prowler
          find . -type f -executable  # Find all executable files

      - name: Run Prowler Scan
        run: |
          cd prowler
          chmod +x ./prowler.py  # Make the Prowler script executable
          python3 ./prowler.py -c check135 > report.txt  # Run the scan using Python
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
