name: Prowler Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prowler-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up AWS CLI
        run: |
          sudo apt-get install -y awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}  # Add this line
         

      - name: Run Prowler
        run: |
          chmod +x ./run_prowler.sh
          ./prowler.sh
