name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Prowler
        run: |
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler

      - name: List Prowler Directory
        run: |
          cd prowler
          ls -lR  # List all files recursively to see the structure

      - name: Run Prowler Scan
        id: prowler
        run: |
          cd prowler
          # Assuming the Prowler executable is directly in this directory
          chmod +x ./prowler  # This might need to be adjusted based on the output
          ./prowler -c check135 > report.txt  # Adjust command if needed
          echo "Scan complete, generating report."

      - name: Send Report to Slack
        run: |
          report=$(cat prowler/report.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected*\\n\`\`\`${report}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
