name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-22.04  # Use a specific version for better compatibility

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clean Environment
        run: |
          pip uninstall -y prowler boto3 botocore cryptography pyOpenSSL || true

      - name: Install Prowler with Compatible Versions
        run: |
          pip install --upgrade pip
          pip install "boto3>=1.26.17,<1.27.0" "botocore>=1.29.0,<1.30.0" prowler

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
          aws configure set region us-east-1

      - name: Run Prowler Scan
        id: prowler_scan
        run: |
          set -e
          report_file="report_check135.txt"
          error_file="error_check135.log"
          echo "Running check: check135"
          if timeout 300 prowler aws -c check135 --output-formats json-asff --output-formats csv --verbose > "$report_file" 2> "$error_file"; then
            echo "Check check135 completed successfully."
            echo "scan_status=success" >> $GITHUB_ENV
          else
            echo "Check check135 failed. See error log for details:"
            cat "$error_file"
            echo "scan_status=failed" >> $GITHUB_ENV
            exit 1
          fi

      - name: Send Reports to Slack
        if: env.scan_status == 'failed'
        run: |
          content=$(<report_check135.txt)
          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*Prowler Alert: Vulnerabilities Detected for report_check135.txt*\\n\`\`\`${content}\`\`\`\"
          }" "${{ secrets.SLACK_WEBHOOK_URL }}"
