name: Prowler Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Clean Environment
        run: |
          pip uninstall -y prowler boto3 botocore cryptography pyOpenSSL || true

      - name: Install Prowler with Compatible Versions
        run: |
          pip install --upgrade pip
          pip install "boto3>=1.26.17,<1.27.0" "botocore>=1.29.0,<1.30.0" prowler

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws configure set aws_session_token "${{ secrets.AWS_SESSION_TOKEN }}"
          aws configure set region eu-north-1  # Ensure this is your desired region

      - name: Run Prowler Scan
        id: prowler_scan
        run: |
          set -e
          report_prefix="prowler-output-$(date +%Y%m%d%H%M%S)"
          report_file_json="${report_prefix}.ocsf.json"
          report_file_csv="${report_prefix}.csv"
          error_file="error_all_checks.log"
          
          echo "Running all checks..."
          if timeout 300 prowler aws -c all --output-formats json-ocsf --output-filename "$report_file_json" --verbose > "$error_file"; then
            prowler aws -c all --output-formats csv --output-filename "$report_file_csv"
            echo "All checks completed successfully."
            echo "scan_status=success" >> $GITHUB_ENV
          else
            echo "Checks failed. See error log for details:"
            cat "$error_file"
            echo "scan_status=failed" >> $GITHUB_ENV
            exit 1
          fi

      - name: Upload Reports to S3
        if: env.scan_status == 'success'
        run: |
          report_prefix="prowler-output-$(date +%Y%m%d%H%M%S)"
          report_file_json="${report_prefix}.ocsf.json"
          report_file_csv="${report_prefix}.csv"
          
          # Upload to S3
          aws s3 cp "$report_file_json" "s3://${{ secrets.S3_BUCKET_NAME }}/$report_file_json" --acl public-read
          aws s3 cp "$report_file_csv" "s3://${{ secrets.S3_BUCKET_NAME }}/$report_file_csv" --acl public-read
          
          # Construct public URLs
          json_url="https://s3.amazonaws.com/${{ secrets.S3_BUCKET_NAME }}/$report_file_json"
          csv_url="https://s3.amazonaws.com/${{ secrets.S3_BUCKET_NAME }}/$report_file_csv"

          echo "json_url=$json_url" >> $GITHUB_ENV
          echo "csv_url=$csv_url" >> $GITHUB_ENV

      - name: Send Reports to Slack
        if: env.scan_status == 'success'
        run: |
          # Prepare the message with links to the reports
          echo "Sending reports to Slack..."

          payload=$(jq -n --arg text "*Prowler Scan Report*\n\nHere are the detailed results:\n\n*JSON Report:* <$json_url|Download>\n*CSV Report:* <$csv_url|Download>" '{text: $text}')

          # Send the message to Slack
          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H 'Content-type: application/json' --data "$payload" "${{ secrets.SLACK_WEBHOOK_URL }}")

          if [ "$response" -ne 200 ]; then
            echo "Failed to send report to Slack. HTTP status code: $response"
            exit 1
          else
            echo "Reports sent to Slack successfully."
          fi
