name: Run Prowler and Upload to S3

on:
  push:
    branches:
      - main   # only run manually when you click "Run workflow"

jobs:
  prowler-scan:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::924144197303:role/github-oidc-terraform-role-21
          aws-region: us-east-1

      - name: Clone prowler
        run: git clone https://github.com/prowler-cloud/prowler.git

      - name: Modify Pydantic Model to Allow Arbitrary Types
        run: |
          # Ensure the Config class with arbitrary_types_allowed=True is added
          sed -i '/class CIS_Requirement_Attribute_Profile(BaseModel):/a \\n    class Config:\n        arbitrary_types_allowed = True' prowler/prowler/lib/check/compliance_models.py
          # Verify the change has been applied
          grep -A 5 'class CIS_Requirement_Attribute_Profile' prowler/prowler/lib/check/compliance_models.py

      - name: Install Prowler dependencies
        run: |
          pip install boto3 pydantic==1.10.2 click rich alive-progress detect-secrets tabulate py-ocsf-models

      - name: Run Prowler
        run: |
          cd prowler
          python3 prowler-cli.py aws -M json-asff -S -o output

      - name: Upload findings to S3
        run: |
          LATEST_FILE=$(ls -t prowler/output/prowler-output-*.asff.json | head -n1)
          if [ -f "$LATEST_FILE" ]; then
            aws s3 cp "$LATEST_FILE" "s3://prowler-t/prowler-raw-reports/"
          else
            echo "❌ No Prowler output file found!"
            exit 1
          fi
