name: Prowler Scan

on:
  push:  # Trigger on push to any branch
    branches:
      - main  # Adjust to your default branch if different
  workflow_dispatch:  # Allows manual triggering

jobs:
  prowler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Prowler
        run: git clone https://github.com/salesforce/prowler.git

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Prowler scan
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Slack webhook if needed
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}      # Slack bot token
        run: python python.py  # Path to your Python script
