name: Prowler Scan 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::924144197303:role/github-oidc-terraform-role-21
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Clone Prowler repository and remove dashboard dependency
        run: |
          # Clone the Prowler repository
          git clone https://github.com/prowler-cloud/prowler.git
          cd prowler

          # Remove the dashboard import statement
          sed -i '/from dashboard.lib.arguments.arguments import init_dashboard_parser/d' prowler/lib/cli/parser.py

          # Install required dependencies
          pip install --upgrade pip
          pip install -r requirements.txt

          # Verify Prowler version
          ./prowler --version

      - name: Run Prowler Scan for Single Account and Store Findings on S3
        run: |
          echo "📌 Running Prowler scan for Account: 924144197303"

          prowler aws \
            --role arn:aws:iam::924144197303:role/ProwlerExecRole \
            --output-formats json-asff \
            --security-hub \
            --ignore-exit-code-3

          echo "✅ Scan completed for Account: 924144197303 and findings sent to Security Hub!"
          
          # Upload findings to S3
          aws s3 cp /home/runner/work/prowler/prowler/output/ "s3://prowler-t/" --recursive

      - name: List Prowler Output
        run: |
          ls -l /home/runner/work/prowler/prowler/output

      - name: Debugging Outputs
        run: |
          echo "Verifying S3 bucket contents:"
          aws s3 ls s3://prowler-t/
