name: Prowler Security Scan

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  prowler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install --upgrade pip  # Upgrade pip to the latest version
          pip install prowler boto3 botocore cryptography==39.0.1 pyOpenSSL==22.0.0  # Specific versions

      - name: Run Prowler Scan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          set -e  # Exit immediately if a command exits with a non-zero status
          for check in check135; do  # You can add more checks if needed
            echo "Running check: $check"
            if prowler aws -c "$check" > "report_$check.txt"; then
              echo "Check $check completed successfully."
            else
              echo "Check $check failed."
              exit 1
            fi
          done
          echo "All scans complete, generated reports:"
          ls -l report_*.txt  # List generated report files

      - name: Send Reports to Slack
        run: |
          if ls report_*.txt 1> /dev/null 2>&1; then
            for report in report_*.txt; do
              content=$(cat "$report")
              curl -X POST -H 'Content-type: application/json' --data "{
                \"text\": \"*Prowler Alert: Vulnerabilities Detected for ${report}*\\n\`\`\`${content}\`\`\`\"
              }" "${{ secrets.SLACK_WEBHOOK_URL }}"
            done
          else
            echo "No report files found to send to Slack."
          fi
